#:schema node_modules/wrangler/config-schema.json
name = "hycu"
compatibility_date = "2025-03-01"
main = "src/index.ts"

[assets]
directory = "public"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "HYCU_KV"
id = "7c5384c1ab3547aca7d3b29ebedc68c9"

[vars]
HYCU_USER_ID = "2024112536"

# Secrets (set via CLI): wrangler secret put API_KEY

[triggers]
crons = ["50 23 * * 0-4"]
# UTC 23:50 = KST 08:50 (Mon-Fri: Sun-Thu UTC)
